# -*- coding: utf-8 -*-
"""fashion_mnist_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QJ7CZjyV-RKryKeBJqnD2t3EYDzfwD8u
"""

import tensorflow as tf

data = tf.keras.datasets.fashion_mnist
(training_images,training_labels),(test_images,test_labels) = data.load_data()
training_images = training_images/255 
test_images = test_images/255

model = tf.keras.Sequential([
tf.keras.layers.Flatten(input_shape = (28,28)),
tf.keras.layers.Dense(128,activation=tf.nn.relu),
tf.keras.layers.Dense(64,activation=tf.nn.relu),
tf.keras.layers.Dense(28,activation=tf.nn.softmax)                        
])

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(training_image,training_labels,epochs=25)

model.evaluate(test_image,test_labels)

classifications = model.predict(test_images)
print(classifications[1])
print(test_labels[1])

